server:
  port: 0
spring:
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true
  datasource:
    url: jdbc:h2:file:./db # в корне проект файл бд db.mv.db
    username: u # имя пользователя консоли
    password: 1 # пароль консоли
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  h2:
    console:
      enabled: true

logging:
  level:
    liquibase: INFO
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
